version: "3"
services:
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    restart: always
    container_name: kmonad-mongodb
    volumes:
      - "./db.init/:/docker-entrypoint-initdb.d/"
  service:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    container_name: kmonad-service
    environment:
      - "DB_HOST=mongodb"
