GET http://localhost:8080/todo
Accept: application/json

###

GET http://localhost:8080/todo/e2c1281f-ad63-44bf-920f-fe78bd5c896c
Accept: application/json

###

POST http://localhost:8080/todo
Accept: application/json
Content-Type: application/json

{
  "id": "9b6a089e-9e92-425f-b4ee-ac1054133159",
  "title": "Title3",
  "description": "Description3",
  "completed": false,
  "createdAt": "2020-01-01T00:00:00",
  "dueDate": "2020-02-02T00:00:00"
}

###

DELETE http://localhost:8080/todo/9b6a089e-9e92-425f-b4ee-ac1054133159
Accept: application/json

###
